export const forecastConstants = {
	ALERT_CLEAR: 'ALERT_CLEAR',
	GET_ALL_REQUEST: 'GET_ALL_REQUEST',
	GET_ALL_SUCCESS: 'GET_ALL_SUCCESS',
	GET_ALL_FAILURE: 'GET_ALL_FAILURE',
	GET_ALERT_SUCCESS: 'GET_ALERT_SUCCESS',
	GET_HOURLY_SUCCESS: 'GET_HOURLY_SUCCESS',
	GET_POINTS_SUCCESS: 'GET_POINTS_SUCCESS'
}